name: workflow to deploy an ARM Template to a resource group
on: 
  push:
    branches: 
      - master
    paths:
      - 'infrastructure/**'

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions

env:
    DEV_CLUSTER_RESOURCE_GROUP: gh-demo-dev
    STAGING_CLUSTER_RESOURCE_GROUP: gh-demo-staging
    PROD_CLUSTER_RESOURCE_GROUP: gh-demo-prod
  
jobs:
  build-and-deploy-to-dev:
    runs-on: ubuntu-latest
    steps:
                
    # Authentication
    # Set up the following secrets in your repository: AZURE_CREDENTIALS
    # For details on usage of secrets, please refer https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS  }}
    
    # Checkout
    - name: Checkout
      uses: actions/checkout@v1
        
    # Deployment of template    
    - name: Provision Dev Azure Resources
      uses: azure/arm-deploy@v1
      with:
        # You can change these environment variables for your configuration:   AZURE_SUBSCRIPTION_ID, AZURE_RESOURCE_GROUP
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.DEV_CLUSTER_RESOURCE_GROUP }}
        template: templates/arm/deploy-dev.json  # Set this to the location of your template file
        parameters: servicePrincipalId=${{ secrets.AZURE_CLIENT_ID }} servicePrincipalSecret=${{ secrets.AZURE_CLIENT_PWD }} 
          
    - name: Provision Staging Azure Resources
      uses: azure/arm-deploy@v1
      with:
        # You can change these environment variables for your configuration:   AZURE_SUBSCRIPTION_ID, AZURE_RESOURCE_GROUP
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.STAGING_CLUSTER_RESOURCE_GROUP }}
        template: templates/arm/deploy-staging.json  # Set this to the location of your template file
        parameters: servicePrincipalId=${{ secrets.AZURE_CLIENT_ID }} servicePrincipalSecret=${{ secrets.AZURE_CLIENT_PWD }} 
        
    - name: Provision Production Azure Resources
      uses: azure/arm-deploy@v1
      with:
        # You can change these environment variables for your configuration:   AZURE_SUBSCRIPTION_ID, AZURE_RESOURCE_GROUP
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.PROD_CLUSTER_RESOURCE_GROUP }}
        template: templates/arm/deploy-prod.json  # Set this to the location of your template file
        parameters: servicePrincipalId=${{ secrets.AZURE_CLIENT_ID }} servicePrincipalSecret=${{ secrets.AZURE_CLIENT_PWD }} 
